#!/bin/sh

NAME=shadowsocks

for server in $(uci -n export $NAME | awk '$2=/servers/{print substr($3,2,9)}'); do
    host=$(uci get $NAME.$server.host 2>/dev/null)
    if [ -n "$host" ]; then
        for ip in $(nslookup $host 1.2.4.8 | awk '/Address /{print $3}' 2>/dev/null); do
	    echo $host
	    echo $ip
            uci set $NAME.$server.server="$ip"
            break
        done
    fi
done

uci commit $NAME

pidof ss-redir >/dev/null || /etc/init.d/$NAME reload
